apiVersion: v1
kind: ServiceAccount
metadata:
  name: fotosintesis-frontend
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: fotosintesis-frontend
    app.kubernetes.io/part-of: fotosintesis-ai
  annotations:
    iam.gke.io/gcp-service-account: __FRONTEND_GCP_SERVICE_ACCOUNT_EMAIL__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fotosintesis-backend
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: fotosintesis-backend
    app.kubernetes.io/part-of: fotosintesis-ai
  annotations:
    iam.gke.io/gcp-service-account: __BACKEND_GCP_SERVICE_ACCOUNT_EMAIL__
