"""Split test_provider_fallback.py and test_system_providers.py under 1,000 lines.

Strategy: extract the shared helper classes (Fake providers) at the
top of each test file into a separate _test_helpers module, then
split the remaining test classes across multiple files.
"""

from __future__ import annotations

import re
from pathlib import Path

DEFINITION_RE = re.compile(r"^(async def |def |class )")
DECORATOR_RE = re.compile(r"^@")


def split_test_file(
    src_path: Path,
    *,
    header_end_marker: str,
    shared_helper_class_names: set[str],
    num_output_files: int,
    output_prefix: str,
    helpers_path: Path,
) -> None:
    text = src_path.read_text()
    lines = text.splitlines(keepends=True)
    # Find the header end (line where the first def/class starts)
    header_match = re.search(header_end_marker, text, re.MULTILINE)
    if not header_match:
        raise SystemExit(f"header marker not found in {src_path}")
    header_end_line = text[: header_match.start()].count("\n")
    header = "".join(lines[:header_end_line])
    body = "".join(lines[header_end_line:])

    body_lines = lines[header_end_line:]
    # Find all top-level def/class definitions
    def_line_indices: list[int] = []
    for idx, line in enumerate(body_lines):
        if DEFINITION_RE.match(line):
            def_line_indices.append(idx)

    # Compute unit starts (include decorators preceding the def)
    unit_starts: list[int] = []
    for line_index in def_line_indices:
        start = line_index
        while start > 0 and DECORATOR_RE.match(body_lines[start - 1]):
            start -= 1
        unit_starts.append(start)
    unit_end_indices = (
        unit_starts[1:] + [len(body_lines)]
    )

    # Identify which units are shared helpers (classes or fixtures)
    shared_helper_lines: set[int] = set()
    shared_helper_fixtures: set[str] = set()
    for i, line_index in enumerate(def_line_indices):
        line = body_lines[line_index]
        name = line.split(":", 1)[0].split("(")[0].split()[-1]
        if name in shared_helper_class_names:
            shared_helper_lines.add(line_index)
        # Heuristic: if a unit is preceded by a @pytest.fixture decorator,
        # treat it as a fixture helper.
        if line_index > 0 and "@pytest.fixture" in body_lines[line_index - 1]:
            shared_helper_lines.add(line_index)
            shared_helper_fixtures.add(name)

    # Build the helpers module
    helpers_chunks: list[str] = []
    for i, line_index in enumerate(def_line_indices):
        if line_index not in shared_helper_lines:
            continue
        start_offset_in_body = sum(len(x) for x in body_lines[: unit_starts[i]])
        end_offset_in_body = sum(len(x) for x in body_lines[: unit_end_indices[i]])
        helpers_chunks.append(body[start_offset_in_body:end_offset_in_body].rstrip())
    if helpers_chunks:
        helpers_path.write_text(
            "from __future__ import annotations\n\n"
            + "# Auto-generated by scripts/split_tests.py\n"
            + f"# Shared helper classes for {src_path.name}.\n\n"
            + header
            + "\n\n\n".join(helpers_chunks)
            + "\n"
        )
        print(f"Wrote {helpers_path}")

    # Build the import block for the part files
    if shared_helper_class_names:
        helpers_import_lines = [
            f"from tests.{helpers_path.stem} import (",
        ]
        for name in sorted(shared_helper_class_names):
            helpers_import_lines.append(f"    {name},")
        helpers_import_lines.append(")")
        helpers_import_block = "\n".join(helpers_import_lines) + "\n\n"
    else:
        helpers_import_block = ""

    # Build the test parts: each non-helper unit is distributed across
    # num_output_files chunks.
    test_unit_indices = [
        i
        for i, line_index in enumerate(def_line_indices)
        if line_index not in shared_helper_lines
    ]
    total = len(test_unit_indices)
    if total == 0:
        return
    chunk_size = (total + num_output_files - 1) // num_output_files
    for chunk_idx in range(num_output_files):
        start_idx = chunk_idx * chunk_size
        end_idx = min((chunk_idx + 1) * chunk_size, total)
        if start_idx >= total:
            break
        chunk_body = "".join(
            body[
                sum(len(x) for x in body_lines[: unit_starts[test_unit_indices[k]]]) :
                sum(len(x) for x in body_lines[: unit_end_indices[test_unit_indices[k]]])
            ].rstrip()
            + "\n\n"
            for k in range(start_idx, end_idx)
        )
        combined = header + helpers_import_block + chunk_body
        out_path = src_path.parent / f"{output_prefix}{chunk_idx + 1}.py"
        out_path.write_text(combined)
        print(
            f"Wrote {out_path}: {end_idx - start_idx} tests, {combined.count(chr(10))} lines"
        )


def main() -> None:
    split_test_file(
        Path("tests/test_provider_fallback.py"),
        header_end_marker=r"^class _FakeModelProvider",
        shared_helper_class_names={
            "_FakeModelProvider",
            "_FakeJudgeProvider",
            "_FakeSearchProvider",
            "_FakeImageAnalysisProvider",
        },
        num_output_files=2,
        output_prefix="test_provider_fallback_part",
        helpers_path=Path("tests/_provider_fallback_helpers.py"),
    )
    split_test_file(
        Path("tests/test_system_providers.py"),
        header_end_marker=r"^@pytest\.fixture\(autouse=True\)",
        shared_helper_class_names=set(),  # no class helpers
        num_output_files=3,
        output_prefix="test_system_providers_part",
        helpers_path=Path("tests/_system_providers_helpers.py"),
    )


if __name__ == "__main__":
    main()
