from __future__ import annotations

# Auto-generated by scripts/split_test_assistant_agent.py
# Shared helpers and constants used across the focused test files.

from datetime import datetime, timezone
import json
import logging
from types import SimpleNamespace
from uuid import UUID, uuid4

import pytest
from sqlalchemy import select

from app.assistant.graph import (
    ASPECT_VALIDATION_GUIDANCE,
    CARE_CLASSIFIER_SCHEMA,
    AnswerabilityResult,
    AssistantGraph,
    _answerability_from_judge_result,
    _aspect_validation_guidance,
    _binomial_from_scientific_name,
    _care_classifier_prompt,
    _grounded_answer_prompt,
    _targeted_web_query,
    _validated_answerability,
    operational_plant_name,
)
from app.assistant import service as assistant_service
from app.assistant.schemas import AssistantChatRequest, AssistantMessage
from app.assistant.service import AssistantService
from app.assistant.tools import AssistantTools, ToolResult
from app.auth.tables import conversation_messages
from app.knowledge.acquisition import TrustedSourceValidator
from app.knowledge.page_evidence import TrustedPageEvidence, TrustedPageEvidenceFetcher
from app.knowledge.plant_data import StructuredPlantEvidence
from app.knowledge.schemas import (
    AcquisitionStatus,
    KnowledgeAcquisitionResult,
    KnowledgeChunk,
    ReviewStatus,
    KnowledgeSourceInput,
)
from app.providers.types import JudgeResult, SearchResult


CONFIRMED_BINOMIAL = "Cotyledon tomentosa"


class FakeTools:
    def __init__(
        self,
        *,
        fail_reminder: bool = False,
        degraded_knowledge: bool = False,
        rag_answerable: bool = True,
        structured_answerable: bool = True,
        web_results: list[SearchResult | TrustedPageEvidence] | None = None,
        fail_web_search: bool = False,
        fail_ingestion: bool = False,
        plant_data: StructuredPlantEvidence | None = None,
        plant_data_ingestion_error: str | None = None,
        model_response: str = "Synthesized model response.",
        fail_model: bool = False,
        model_error_message: str | None = None,
        classifier_data: dict | None = None,
        fail_classifier: bool = False,
        knowledge_content: str = "Requires moderate watering and well-draining substrate.",
        judge_scores: list[float] | None = None,
    ) -> None:
        self.fail_reminder = fail_reminder
        self.degraded_knowledge = degraded_knowledge
        self.rag_answerable = rag_answerable
        self.structured_answerable = structured_answerable
        self.web_results = web_results or []
        self.fail_web_search = fail_web_search
        self.fail_ingestion = fail_ingestion
        self.created_reminders = 0
        self.reminder_kwargs = None
        self.web_search_calls = 0
        self.web_search_query = None
        self.ingestion_calls = 0
        self.ingestion_kwargs = None
        self.knowledge_search_kwargs = None
        self.plant_data = plant_data
        self.plant_data_ingestion_error = plant_data_ingestion_error
        self.plant_data_calls = 0
        self.plant_data_kwargs = None
        self.model_response = model_response
        self.fail_model = fail_model
        self.model_error_message = model_error_message
        self.classifier_data = classifier_data
        self.fail_classifier = fail_classifier
        self.knowledge_content = knowledge_content
        self.model_calls = 0
        self.model_prompts: list[str] = []
        self.classifier_calls = 0
        self.call_order: list[str] = []
        self.judge_calls: list[dict] = []
        self.judge_scores = list(judge_scores or [])
        self.providers = SimpleNamespace(judge=self)

    async def generate_json(self, prompt: str, schema: dict, **kwargs) -> ToolResult:
        self.classifier_calls += 1
        if self.fail_classifier:
            return ToolResult(ok=False, error="classifier unavailable")
        if self.classifier_data:
            return ToolResult(ok=True, data=self.classifier_data)
        message_start = prompt.rfind("\nMessage: ")
        message_text = prompt[message_start + 10:].strip() if message_start >= 0 else prompt
        lowered = message_text.casefold()
        if "ignora las instrucciones" in lowered:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "unsafe_or_injection",
                "topic": "unknown",
                "required_aspects": [],
                "plant_reference": "Pata",
                "confidence": 0.95,
                "needs_retrieval": False,
            }
        elif "recordatorio" in lowered or "recordame" in lowered:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "reminder_request",
                "topic": "unknown",
                "required_aspects": [],
                "plant_reference": "Pata",
                "confidence": 0.92,
                "needs_retrieval": False,
            }
        elif "mascota" in lowered or "gato" in lowered or "perro" in lowered or "tox" in lowered:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "plant_care_question",
                "topic": "toxicity_safety",
                "required_aspects": ["toxicity_pet_safety"],
                "plant_reference": "Pata",
                "confidence": 0.92,
                "needs_retrieval": True,
            }
        elif "luz" in lowered or "sol" in lowered or "sombra" in lowered or "light" in lowered:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "plant_care_question",
                "topic": "light",
                "required_aspects": ["light_exposure"],
                "plant_reference": "Pata",
                "confidence": 0.92,
                "needs_retrieval": True,
            }
        elif "nativa" in lowered:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "plant_care_question",
                "topic": "taxonomy",
                "required_aspects": ["taxonomy_native_range"],
                "plant_reference": "Pata",
                "confidence": 0.92,
                "needs_retrieval": True,
            }
        else:
            data = {
                "language": "es",
                "answer_language": "es",
                "intent": "plant_care_question",
                "topic": "watering",
                "required_aspects": ["watering_frequency_or_trigger"],
                "plant_reference": "Pata",
                "confidence": 0.92,
                "needs_retrieval": True,
            }
        return ToolResult(ok=True, data=data)

    async def garden_lookup(self, *, user_id: UUID) -> ToolResult:
        return ToolResult(
            ok=True,
            data=[
                {
                    "id": uuid4(),
                    "nickname": "Pata",
                    "scientific_name": "Cotyledon tomentosa",
                    "common_name": "Pata de oso",
                },
                {
                    "id": uuid4(),
                    "nickname": "Monstera",
                    "scientific_name": "Monstera deliciosa",
                    "common_name": "Monstera",
                },
            ],
        )

    async def knowledge_search(
        self,
        *,
        scientific_name: str,
        topic: str,
        required_aspects: list[str] | None = None,
        question: str | None = None,
    ) -> ToolResult:
        self.call_order.append("rag")
        self.knowledge_search_kwargs = {
            "scientific_name": scientific_name,
            "topic": topic,
            "required_aspects": required_aspects or [],
            "question": question,
        }
        if self.degraded_knowledge:
            return ToolResult(
                ok=True,
                data=KnowledgeAcquisitionResult(
                    status=AcquisitionStatus.degraded,
                    chunks=[],
                    limitations=["No trusted approved source was found."],
                    retry_available=True,
                    manual_search_url="https://www.google.com/search?q=trusted",
                ),
            )
        return ToolResult(
            ok=True,
            data=KnowledgeAcquisitionResult(
                status=AcquisitionStatus.retrieved,
                chunks=[
                    KnowledgeChunk(
                        chunk_index=0,
                        content=self.knowledge_content,
                        metadata={"title": "Botanical record"},
                        scientific_name=scientific_name,
                        topic=topic,
                        source_domain="example.org",
                        source_url="https://example.org/source",
                        confidence=0.85,
                        review_status=ReviewStatus.auto_ingested,
                        retrieved_at=datetime.now(timezone.utc),
                    )
                ],
            ),
        )

    async def reminder_create(self, **kwargs) -> ToolResult:
        if self.fail_reminder:
            return ToolResult(ok=False, error="reminder_create failed: database unavailable")
        self.created_reminders += 1
        self.reminder_kwargs = kwargs
        return ToolResult(ok=True, data={"id": str(uuid4())})

    async def light_measurement_lookup(self, **kwargs) -> ToolResult:
        return ToolResult(ok=True, data=None)

    async def trusted_web_search(
        self, query: str, *, candidates: list[SearchResult] | None = None
    ) -> ToolResult:
        self.call_order.append("web")
        if candidates is None:
            self.web_search_calls += 1
        self.web_search_query = query
        if self.fail_web_search:
            return ToolResult(ok=False, error="trusted_web_search failed: unavailable")
        return ToolResult(ok=True, data=candidates or self.web_results)

    async def generate_text(self, prompt: str) -> ToolResult:
        self.model_calls += 1
        self.model_prompts.append(prompt)
        if self.fail_model:
            from app.assistant.tools import AssistantFailureMetadata, ProviderFailureEntry
            error = self.model_error_message or "model_generate_text failed: unavailable"
            if "all providers failed" in error.lower():
                category = "all_providers_failed"
                retryable = False
                transient = False
            elif "service unavailable" in error.lower():
                category = "service_unavailable"
                retryable = False
                transient = False
            elif "timeout" in error.lower():
                category = "timeout"
                retryable = False
                transient = False
            elif "rate limit" in error.lower():
                category = "rate_limit"
                retryable = False
                transient = False
            else:
                category = "unknown"
                retryable = True
                transient = True
            metadata = AssistantFailureMetadata(
                failure_category=category,
                retryable=retryable,
                transient=transient,
                provider_failures=[
                    ProviderFailureEntry(
                        provider="gemini",
                        role="model",
                        operation="generate_text",
                        failure_category=category,
                        retryable=retryable,
                        transient=transient,
                    )
                ],
            )
            return ToolResult(ok=False, error=error, failure_metadata=metadata)
        if prompt.startswith("Render a fallback response"):
            if "Intent: missing_confirmed_taxonomy" in prompt:
                return ToolResult(ok=True, data="I need the confirmed scientific name of the plant before I can look up reliable care evidence.")
            if "Intent: out_of_domain" in prompt:
                return ToolResult(ok=True, data="I can help with plant care, identification, light, reminders, and your garden. Please rephrase your question within that scope.")
            if "Intent: conservative_pet_safety_fallback" in prompt:
                return ToolResult(ok=True, data="I did not find direct and reliable evidence about pet safety. As a precaution, keep it out of reach of pets and consult a veterinarian or animal poison control center if there is ingestion with symptoms.")
            if "Intent: conservative_human_edibility_fallback" in prompt:
                return ToolResult(ok=True, data="I did not find direct and reliable evidence about whether it is edible. For safety, do not consume it until you verify with a reliable toxicological or botanical source.")
            if "Intent: degraded_evidence" in prompt:
                return ToolResult(ok=True, data="I did not find enough evidence in the knowledge base. No trusted approved source was found.")
            if "Intent: ambiguous_plant_clarification" in prompt:
                return ToolResult(ok=True, data="Which plant would you like to ask about? In your garden I see: Pata, Monstera.")
            if "Intent: unsafe_or_injection" in prompt:
                return ToolResult(ok=True, data="I cannot follow instructions that try to change my rules or activate tools without permission.")
            if "Intent: reminder_action_failed" in prompt:
                return ToolResult(ok=True, data="I could not create the reminder. The action was not completed.")
            if "Intent: reminder_missing_data" in prompt:
                if "date or time" in prompt:
                    return ToolResult(ok=True, data="To create the reminder I need: date or time.")
                return ToolResult(ok=True, data="To create the reminder I need: recurrence.")
            if "Intent: model_generation_failed" in prompt:
                return ToolResult(ok=True, data="Model-rendered fallback response.")
        return ToolResult(ok=True, data=self.model_response)

    async def judge_response(self, payload: dict, rubric: dict, **kwargs) -> object:
        self.judge_calls.append({"payload": payload, "rubric": rubric})
        evidence_type = payload.get("evidence_type")
        answerable = True if evidence_type in {"live_web", "combined_rag_web"} else self.structured_answerable if evidence_type == "structured_api" else self.rag_answerable
        score = (
            self.judge_scores.pop(0)
            if evidence_type in {"live_web", "combined_rag_web"} and self.judge_scores
            else 1.0 if answerable else 0.0
        )
        required_aspects = list(payload.get("required_aspects") or ["watering_frequency_or_trigger"])
        source_metadata = [source for source in payload.get("source_metadata") or [] if source.get("url")]
        live_sources = [source for source in source_metadata if source.get("evidence_type") == "live_web"]
        supported_source = (live_sources or source_metadata or [{"url": "https://example.org/source"}])[0]
        source_support = [
            {
                "claim": "Evidence directly supports the requested plant-care answer.",
                "source_urls": [supported_source["url"]],
                "covered_aspects": required_aspects,
                "evidence_quote": "Evidence directly supports the requested plant-care answer.",
                "confidence": score,
            }
        ] if answerable else []
        return SimpleNamespace(
            score=score,
            passed=answerable,
            status="full" if answerable else "insufficient",
            covered_aspects=required_aspects if answerable else [],
            missing_aspects=[] if answerable else required_aspects,
            source_support=source_support,
            contradictions=[],
            confidence=score,
            reasons=[] if answerable else [f"{evidence_type} evidence does not answer question"],
        )

    async def ingest_web_evidence(self, **kwargs) -> ToolResult:
        self.ingestion_calls += 1
        self.ingestion_kwargs = kwargs
        if self.fail_ingestion:
            return ToolResult(ok=False, error="ingest_web_evidence failed: unavailable")
        return ToolResult(ok=True, data={"document_id": str(uuid4())})

    async def plant_data_lookup(self, *, scientific_name: str, topic: str) -> ToolResult:
        self.call_order.append("plant_data")
        self.plant_data_calls += 1
        self.plant_data_kwargs = {"scientific_name": scientific_name, "topic": topic}
        if not self.plant_data:
            return ToolResult(ok=True, data=None)
        return ToolResult(
            ok=True,
            data={
                "evidence": self.plant_data,
                "ingestion_error": self.plant_data_ingestion_error,
            },
        )


class RollbackRecordingKnowledgeRepository:
    def __init__(self) -> None:
        self.rollback_calls = 0

    async def rollback(self) -> None:
        self.rollback_calls += 1


def _structured_evidence(
    *, sufficient: bool = True, confidence: float = 0.72
) -> StructuredPlantEvidence:
    return StructuredPlantEvidence(
        scientific_name="Cotyledon tomentosa",
        topic="watering",
        content="Watering: Let soil dry between waterings. Providers: mock-trefle, mock-perenual.",
        confidence=confidence,
        sources=[
            KnowledgeSourceInput(
                title="mock-trefle structured plant data",
                url="https://trefle.io/mock/species/cotyledon-tomentosa",
                source_domain="trefle.io",
                retrieved_at=datetime.now(timezone.utc),
                validation_status="structured_api",
            )
        ],
        providers=["mock-trefle", "mock-perenual"],
        fields={"watering": "Let soil dry between waterings."},
        sufficient=sufficient,
        missing_fields=[] if sufficient else ["watering"],
    )


def _validated_web_metadata(*, covered_aspects: list[str] | None = None) -> dict[str, object]:
    covered = covered_aspects or ["watering_frequency_or_trigger"]
    return {
        "topic": "watering",
        "required_aspects": covered,
        "covered_aspects": covered,
        "language": "en",
        "evidence_type": "validated_web",
        "validation_confidence": 0.86,
        "source_domain": "example.org",
        "review_status": "auto_ingested",
    }


class StrongWateringJudgeTools(FakeTools):
    """Judge returns full status with low confidence (0.35) but structurally strong."""

    async def judge_response(self, payload, rubric, **kwargs):
        evidence_type = payload.get("evidence_type")
        required_aspects = list(payload.get("required_aspects") or ["watering_frequency_or_trigger"])
        if evidence_type == "rag":
            return SimpleNamespace(
                score=0.35,
                passed=True,
                status="full",
                covered_aspects=required_aspects,
                missing_aspects=[],
                source_support=[
                    {
                        "claim": "Water when soil is dry.",
                        "source_urls": ["https://example.org/watering"],
                        "covered_aspects": required_aspects,
                        "evidence_quote": "Water when the top inch of soil is dry.",
                        "confidence": 0.35,
                    }
                ],
                contradictions=[],
                confidence=0.35,
                reasons=["evidence directly answers watering question"],
            )
        return await super().judge_response(payload, rubric, **kwargs)


class LowConfidenceSafetyJudgeTools(FakeTools):
    """Judge returns full status with low confidence (0.35) for safety aspect."""

    async def judge_response(self, payload, rubric, **kwargs):
        evidence_type = payload.get("evidence_type")
        required_aspects = list(payload.get("required_aspects") or ["toxicity_pet_safety"])
        if evidence_type == "rag":
            return SimpleNamespace(
                score=0.35,
                passed=True,
                status="full",
                covered_aspects=required_aspects,
                missing_aspects=[],
                source_support=[
                    {
                        "claim": "This plant may be toxic to pets.",
                        "source_urls": ["https://example.org/toxicity"],
                        "covered_aspects": required_aspects,
                        "evidence_quote": "Toxic to cats and dogs.",
                        "confidence": 0.35,
                    }
                ],
                contradictions=[],
                confidence=0.35,
                reasons=["evidence addresses pet toxicity"],
            )
        return await super().judge_response(payload, rubric, **kwargs)


class PartialLowConfidenceJudgeTools(FakeTools):
    """Judge returns partial status with low confidence (0.35) for watering + light."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.classifier_data = {
            "language": "en",
            "answer_language": "en",
            "intent": "plant_care_question",
            "topic": "watering",
            "required_aspects": ["watering_frequency_or_trigger", "light_exposure"],
            "plant_reference": "Cotyledon tomentosa",
            "confidence": 0.92,
            "needs_retrieval": True,
        }

    async def judge_response(self, payload, rubric, **kwargs):
        evidence_type = payload.get("evidence_type")
        required_aspects = list(
            payload.get("required_aspects") or ["watering_frequency_or_trigger", "light_exposure"]
        )
        if evidence_type == "rag":
            return SimpleNamespace(
                score=0.35,
                passed=False,
                status="partial",
                covered_aspects=required_aspects,
                missing_aspects=[],
                source_support=[
                    {
                        "claim": "Water when soil is dry and provide bright indirect light.",
                        "source_urls": ["https://example.org/care"],
                        "covered_aspects": required_aspects,
                        "evidence_quote": "Water when dry, bright indirect light.",
                        "confidence": 0.35,
                    }
                ],
                contradictions=[],
                confidence=0.35,
                reasons=["evidence partially answers the question"],
            )
        return await super().judge_response(payload, rubric, **kwargs)


class HighConfidencePartialJudgeTools(FakeTools):
    """Judge returns partial status with high confidence (0.80)."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.classifier_data = {
            "language": "en",
            "answer_language": "en",
            "intent": "plant_care_question",
            "topic": "watering",
            "required_aspects": ["watering_frequency_or_trigger", "light_exposure"],
            "plant_reference": "Cotyledon tomentosa",
            "confidence": 0.92,
            "needs_retrieval": True,
        }

    async def judge_response(self, payload, rubric, **kwargs):
        evidence_type = payload.get("evidence_type")
        if evidence_type == "rag":
            return SimpleNamespace(
                score=0.80,
                passed=False,
                status="partial",
                covered_aspects=["watering_frequency_or_trigger"],
                missing_aspects=["light_exposure"],
                source_support=[
                    {
                        "claim": "Water when soil is dry.",
                        "source_urls": ["https://example.org/watering"],
                        "covered_aspects": ["watering_frequency_or_trigger"],
                        "evidence_quote": "Water when the top inch of soil is dry.",
                        "confidence": 0.80,
                    }
                ],
                contradictions=[],
                confidence=0.80,
                reasons=["evidence supports watering but not light"],
            )
        return await super().judge_response(payload, rubric, **kwargs)


class SlowJudgeTools(FakeTools):
    """Judge that always times out."""

    async def judge_response(self, payload, rubric, **kwargs):
        import asyncio
        await asyncio.sleep(100)
        return SimpleNamespace(score=1.0, passed=True, status="full")


class SlowWebSearchTools(FakeTools):
    """Web search that always times out."""

    async def trusted_web_search(self, query, *, candidates=None):
        import asyncio
        await asyncio.sleep(100)
        return ToolResult(ok=True, data=[])


PEST_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "pests",
    "required_aspects": [
        "pest_identification",
        "pest_isolation_steps",
        "pest_prevention_steps",
    ],
    "plant_reference": "Pata",
    "confidence": 0.9,
    "needs_retrieval": True,
}


SAFETY_PET_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "toxicity_safety",
    "required_aspects": ["toxicity_pet_safety"],
    "plant_reference": "Pata",
    "confidence": 0.92,
    "needs_retrieval": True,
}


def test_general_guidance_prompt_requires_separation_and_safety_prohibitions() -> None:
    """Prompt builder must enforce separation, language, and safety prohibitions."""
    from app.assistant.graph import _general_guidance_with_disclaimer_prompt

    prompt = _general_guidance_with_disclaimer_prompt(
        user_message="Veo unos insectos blancos pequenos debajo de las hojas",
        plant_name="Pata",
        topic="pests",
        answer_language="es",
        required_aspects=["pest_identification", "pest_isolation_steps"],
        covered_aspects=[],
        missing_aspects=["pest_identification", "pest_isolation_steps"],
        source_support=[],
        source_metadata=[],
    )

    assert "answer_language (es)" in prompt
    assert "plain text only" in prompt
    assert "What the sources validated" in prompt
    assert "What the sources did not validate" in prompt
    assert "General unvalidated guidance" in prompt
    assert "Details that would help" in prompt
    assert "do not cite any source" in prompt
    assert "insecticides" in prompt
    assert "toxicity" in prompt
    assert "edibility" in prompt
    assert "Answerability status: insufficient" in prompt


SAFETY_PET_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "toxicity_safety",
    "required_aspects": ["toxicity_pet_safety"],
    "plant_reference": "Pata",
    "confidence": 0.92,
    "needs_retrieval": True,
}


CHEMICAL_TREATMENT_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "pests",
    "required_aspects": [
        "safety_chemical_treatment_precautions",
        "pest_treatment_action",
    ],
    "plant_reference": "Pata",
    "confidence": 0.9,
    "needs_retrieval": True,
}


PESTICIDE_INSTRUCTION_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "pests",
    "required_aspects": [
        "safety_chemical_treatment_precautions",
        "pest_treatment_action",
    ],
    "plant_reference": "Pata",
    "confidence": 0.88,
    "needs_retrieval": True,
}


SAFETY_BOUNDARY_CASES = [
    pytest.param(
        SAFETY_PET_CLASSIFIER,
        "Es toxica para gatos mi Pata?",
        id="pet_safety",
    ),
    pytest.param(
        CHEMICAL_TREATMENT_CLASSIFIER,
        "Que precauciones debo tomar al aplicar un tratamiento quimico a mi Pata?",
        id="chemical_treatment_precautions",
    ),
    pytest.param(
        {
            "language": "es",
            "answer_language": "es",
            "intent": "plant_care_question",
            "topic": "pests",
            "required_aspects": [
                "safety_disposal_precautions",
                "pest_treatment_action",
            ],
            "plant_reference": "Pata",
            "confidence": 0.9,
            "needs_retrieval": True,
        },
        "Como desecho de forma segura los residuos del tratamiento de mi Pata?",
        id="safety_disposal_precautions",
    ),
]


@pytest.mark.asyncio
@pytest.mark.parametrize("classifier,message", SAFETY_BOUNDARY_CASES)
async def test_unsupported_safety_missing_aspects_avoid_disclaimed_guidance(
    classifier: dict,
    message: str,
) -> None:
    """Safety-sensitive missing aspects must never route to the disclaimed branch."""
    tools = FakeTools(
        rag_answerable=False,
        plant_data=None,
        web_results=[],
        classifier_data=classifier,
    )

    result = await AssistantGraph(tools).run(
        user_id=uuid4(),
        message=message,
        plant_hint=None,
        plant_binomial_name=CONFIRMED_BINOMIAL,
    )

    assert result.get("llm_general_guidance_used") is not True
    assert result.get("ingestion_claims", []) == []
    assert result.get("source_support", []) == []

    disclaimed_prompts = [
        p for p in tools.model_prompts
        if "What the sources validated" in p and "General unvalidated guidance" in p
    ]
    assert disclaimed_prompts == []

    diagnostics = result["diagnostics"]
    assert diagnostics["llm_general_guidance_used"] is False

    assert "conservative_safety_fallback" in result["fallback_reasons"]
    assert result["answer"] is not None
    lowered_answer = result["answer"].casefold()
    for forbidden in (
        "insecticide",
        "pesticide",
        "imidacloprid",
        "malathion",
        "dose",
        "ml per liter",
        "grams per liter",
    ):
        assert forbidden not in lowered_answer


PESTICIDE_INSTRUCTION_CLASSIFIER = {
    "language": "en",
    "answer_language": "en",
    "intent": "plant_care_question",
    "topic": "pests",
    "required_aspects": [
        "safety_chemical_treatment_precautions",
        "pest_treatment_action",
    ],
    "plant_reference": "Pata",
    "confidence": 0.88,
    "needs_retrieval": True,
}


SAFETY_BOUNDARY_CASES = [
    pytest.param(
        SAFETY_PET_CLASSIFIER,
        "Es toxica para gatos mi Pata?",
        id="pet_safety",
    ),
    pytest.param(
        CHEMICAL_TREATMENT_CLASSIFIER,
        "Que precauciones debo tomar al aplicar un tratamiento quimico a mi Pata?",
        id="chemical_treatment_precautions",
    ),
    pytest.param(
        {
            "language": "es",
            "answer_language": "es",
            "intent": "plant_care_question",
            "topic": "pests",
            "required_aspects": [
                "safety_disposal_precautions",
                "pest_treatment_action",
            ],
            "plant_reference": "Pata",
            "confidence": 0.9,
            "needs_retrieval": True,
        },
        "Como desecho de forma segura los residuos del tratamiento de mi Pata?",
        id="safety_disposal_precautions",
    ),
]

# All symbols defined here are re-exported as a single namespace by
# the focused test parts via ``from tests._assistant_helpers import *``.
# The test parts share the original header imports; ruff only flags
# the F401s on the helpers module when ``__all__`` is defined here.
