from __future__ import annotations

import asyncio
from typing import Any

from app.providers.interfaces import (
    ImageAnalysisProvider,
    JudgeEvaluationProvider,
    ModelProvider,
    SearchProvider,
)
from app.providers.types import (
    ImageAnalysisResult,
    JudgeResult,
    JsonGenerationResult,
    SearchResult,
    TextGenerationResult,
)


# Auto-generated by scripts/split_tests.py
# Shared helper classes for test_provider_fallback.py.


async def _async_sleep(seconds: float) -> None:
    await asyncio.sleep(seconds)


# ---------------------------------------------------------------------------
# Helper: Fake providers for testing
# ---------------------------------------------------------------------------

class _FakeModelProvider(ModelProvider):
    def __init__(
        self,
        *,
        name: str = "fake-model",
        fail_generate_text: bool = False,
        fail_generate_json: bool = False,
        fail_judge: bool = False,
        invalid_json: bool = False,
        semantic_insufficient: bool = False,
        latency: float = 0.0,
        non_transient: bool = False,
    ) -> None:
        self.provider_name = name
        self._fail_text = fail_generate_text
        self._fail_json = fail_generate_json
        self._fail_judge = fail_judge
        self._invalid_json = invalid_json
        self._semantic_insufficient = semantic_insufficient
        self._latency = latency
        self._non_transient = non_transient

    async def generate_text(self, prompt: str, **kwargs: Any) -> TextGenerationResult:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail_text:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        return TextGenerationResult(
            provider=self.provider_name,
            model="test-model",
            text=f"{self.provider_name} response to: {prompt[:40]}",
        )

    async def generate_json(
        self, prompt: str, schema: dict[str, Any], **kwargs: Any
    ) -> JsonGenerationResult:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail_json:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        if self._invalid_json:
            raise RuntimeError(f"{self.provider_name} invalid structured output")
        return JsonGenerationResult(
            provider=self.provider_name,
            model="test-model",
            data={"result": f"{self.provider_name} json data"},
        )

    async def judge_response(
        self, payload: dict[str, Any], rubric: dict[str, Any], **kwargs: Any
    ) -> JudgeResult:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail_judge:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        if self._semantic_insufficient:
            return JudgeResult(
                provider=self.provider_name,
                model="test-model",
                score=0.0,
                passed=False,
                reasons=["Insufficient evidence"],
                status="insufficient",
                confidence=0.0,
            )
        return JudgeResult(
            provider=self.provider_name,
            model="test-model",
            score=1.0,
            passed=True,
            status="full",
            reasons=[],
            confidence=1.0,
        )


class _FakeJudgeProvider(JudgeEvaluationProvider):
    def __init__(
        self,
        *,
        name: str = "fake-judge",
        fail: bool = False,
        semantic_insufficient: bool = False,
        invalid_output: bool = False,
        latency: float = 0.0,
        non_transient: bool = False,
    ) -> None:
        self.provider_name = name
        self._fail = fail
        self._semantic_insufficient = semantic_insufficient
        self._invalid_output = invalid_output
        self._latency = latency
        self._non_transient = non_transient

    async def judge_response(
        self, payload: dict[str, Any], rubric: dict[str, Any], **kwargs: Any
    ) -> JudgeResult:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        if self._invalid_output:
            raise RuntimeError(f"{self.provider_name} invalid structured output")
        if self._semantic_insufficient:
            return JudgeResult(
                provider=self.provider_name,
                model="test-model",
                score=0.0,
                passed=False,
                reasons=["Insufficient evidence"],
                status="insufficient",
                confidence=0.0,
            )
        return JudgeResult(
            provider=self.provider_name,
            model="test-model",
            score=1.0,
            passed=True,
            status="full",
            reasons=[],
            confidence=1.0,
        )


class _FakeSearchProvider(SearchProvider):
    def __init__(
        self,
        *,
        name: str = "fake-search",
        fail: bool = False,
        empty_results: bool = False,
        latency: float = 0.0,
        non_transient: bool = False,
    ) -> None:
        self.provider_name = name
        self._fail = fail
        self._empty = empty_results
        self._latency = latency
        self._non_transient = non_transient

    async def search(self, query: str, **kwargs: Any) -> list[SearchResult]:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        if self._empty:
            return []
        return [
            SearchResult(
                title=f"{self.provider_name} result",
                url=f"https://{self.provider_name}.example.com/result",
                snippet=f"{self.provider_name} search for {query[:30]}",
                source_domain=f"{self.provider_name}.example.com",
            )
        ]


class _FakeImageAnalysisProvider(ImageAnalysisProvider):
    def __init__(
        self,
        *,
        name: str = "fake-vision",
        fail: bool = False,
        latency: float = 0.0,
        non_transient: bool = False,
    ) -> None:
        self.provider_name = name
        self._fail = fail
        self._latency = latency
        self._non_transient = non_transient

    async def analyze_image(
        self, image: bytes, prompt: str | None = None, **kwargs: Any
    ) -> ImageAnalysisResult:
        if self._latency:
            await _async_sleep(self._latency)
        if self._fail:
            if self._non_transient:
                raise ValueError(f"{self.provider_name} configuration error")
            raise RuntimeError(f"{self.provider_name} service unavailable")
        return ImageAnalysisResult(
            provider=self.provider_name,
            model="test-model",
            description=f"{self.provider_name} analysis",
        )
