from __future__ import annotations

# Auto-generated by scripts/split_tests.py
# Shared helper classes for test_system_providers.py.

import sys
import types

import pytest

from app.core.settings import get_settings


@pytest.fixture(autouse=True)
def reset_provider_settings(monkeypatch: pytest.MonkeyPatch) -> None:
    for chain_var in (
        "MODEL_PROVIDERS",
        "JUDGE_PROVIDERS",
        "SEARCH_PROVIDERS",
        "VISION_PROVIDERS",
    ):
        monkeypatch.setenv(chain_var, "[]")
    monkeypatch.setenv("MODEL_PROVIDER", "mock")
    monkeypatch.setenv("VISION_PROVIDER", "mock")
    monkeypatch.setenv("JUDGE_PROVIDER", "mock")
    monkeypatch.setenv("SEARCH_PROVIDER", "mock")
    monkeypatch.setenv("EMBEDDING_PROVIDER", "mock")
    monkeypatch.setenv("TREFLE_PROVIDER", "mock")
    monkeypatch.setenv("PERENUAL_PROVIDER", "mock")
    monkeypatch.setenv("OPENAI_API_KEY", "")
    monkeypatch.setenv("GEMINI_API_KEY", "")
    monkeypatch.setenv("TREFLE_API_KEY", "")
    monkeypatch.setenv("PERENUAL_API_KEY", "")
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


@pytest.fixture
def fake_openai_module(monkeypatch: pytest.MonkeyPatch) -> None:
    class FakeResponses:
        async def create(self, **kwargs: object) -> object:
            return types.SimpleNamespace(output_text='{"score": 1, "passed": true, "reasons": []}')

    class FakeEmbeddings:
        async def create(self, **kwargs: object) -> object:
            return types.SimpleNamespace(
                data=[types.SimpleNamespace(index=0, embedding=[0.1, 0.2, 0.3])],
                usage=types.SimpleNamespace(prompt_tokens=3, total_tokens=3),
            )

    class FakeAsyncOpenAI:
        def __init__(self, *, api_key: str) -> None:
            self.api_key = api_key
            self.responses = FakeResponses()
            self.embeddings = FakeEmbeddings()

    monkeypatch.setitem(sys.modules, "openai", types.SimpleNamespace(AsyncOpenAI=FakeAsyncOpenAI))


@pytest.fixture
def fake_gemini_module(monkeypatch: pytest.MonkeyPatch) -> None:
    google_module = types.ModuleType("google")
    genai_module = types.ModuleType("google.genai")
    genai_types_module = types.ModuleType("google.genai.types")

    class FakeGenerateContentConfig:
        def __init__(self, **kwargs: object) -> None:
            self.kwargs = kwargs

    class FakePart:
        @staticmethod
        def from_bytes(*, data: bytes, mime_type: str) -> dict[str, object]:
            return {"data": data, "mime_type": mime_type}

    class FakeGoogleSearch:
        pass

    class FakeTool:
        def __init__(self, **kwargs: object) -> None:
            self.kwargs = kwargs

    class FakeModels:
        async def generate_content(self, **kwargs: object) -> object:
            return types.SimpleNamespace(text='{"score": 1, "passed": true, "reasons": []}')

    class FakeClient:
        def __init__(self, *, api_key: str) -> None:
            self.api_key = api_key
            self.aio = types.SimpleNamespace(models=FakeModels())

    genai_types_module.GenerateContentConfig = FakeGenerateContentConfig
    genai_types_module.Part = FakePart
    genai_types_module.GoogleSearch = FakeGoogleSearch
    genai_types_module.Tool = FakeTool
    genai_module.Client = FakeClient
    genai_module.types = genai_types_module
    google_module.genai = genai_module
    monkeypatch.setitem(sys.modules, "google", google_module)
    monkeypatch.setitem(sys.modules, "google.genai", genai_module)
    monkeypatch.setitem(sys.modules, "google.genai.types", genai_types_module)
