import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";


const root = process.cwd();

describe("OpenAPI-generated frontend contracts", () => {
  it("keeps generated OpenAPI contracts and uses them from the runtime wrapper", async () => {
    const [generatedTypes, schema, runtimeClient, packageJson] = await Promise.all([
      readFile(resolve(root, "src/lib/generated/openapi.d.ts"), "utf8"),
      readFile(resolve(root, "src/lib/generated/openapi.json"), "utf8"),
      readFile(resolve(root, "src/lib/api/client.ts"), "utf8"),
      readFile(resolve(root, "package.json"), "utf8"),
    ]);

    expect(generatedTypes).toContain("This file was auto-generated by openapi-typescript.");
    expect(generatedTypes).toContain("HomeSummaryResponse");
    expect(schema).toContain('"/home/summary"');
    expect(runtimeClient).toContain('import type { components } from "@/lib/generated/openapi"');
    expect(runtimeClient).not.toContain("type HomeSummaryResponse = {");
    expect(packageJson).toContain("openapi:generate");
    expect(packageJson).toContain("openapi:check");
  });

  it("keeps candidate enrichment metadata bounded and privacy-shaped", async () => {
    const schema = JSON.parse(
      await readFile(resolve(root, "src/lib/generated/openapi.json"), "utf8"),
    );
    const statusProperties = schema.components.schemas.CandidateEnrichmentStatus.properties;
    const jobProperties = schema.components.schemas.JobStatusResponse.properties;

    expect(Object.keys(statusProperties).sort()).toEqual(["candidate_id", "job", "policy_version"]);
    expect(jobProperties).not.toHaveProperty("payload");
    expect(jobProperties).not.toHaveProperty("evidence");
    expect(jobProperties).not.toHaveProperty("claims");
    expect(jobProperties).not.toHaveProperty("quotes");
    expect(jobProperties).not.toHaveProperty("prompts");
  });
});
