import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";


const root = process.cwd();

describe("OpenAPI-generated frontend contracts", () => {
  it("keeps generated OpenAPI contracts and uses them from the runtime wrapper", async () => {
    const [generatedTypes, schema, runtimeClient, packageJson] = await Promise.all([
      readFile(resolve(root, "src/lib/generated/openapi.d.ts"), "utf8"),
      readFile(resolve(root, "src/lib/generated/openapi.json"), "utf8"),
      readFile(resolve(root, "src/lib/api/client.ts"), "utf8"),
      readFile(resolve(root, "package.json"), "utf8"),
    ]);

    expect(generatedTypes).toContain("This file was auto-generated by openapi-typescript.");
    expect(generatedTypes).toContain("HomeSummaryResponse");
    expect(schema).toContain('"/home/summary"');
    expect(runtimeClient).toContain('import type { components } from "@/lib/generated/openapi"');
    expect(runtimeClient).not.toContain("type HomeSummaryResponse = {");
    expect(packageJson).toContain("openapi:generate");
    expect(packageJson).toContain("openapi:check");
  });
});
